hbd/config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :userprofiles
  get 'test/index'

  resources :births
  get 'profile/my'

  get '/profile_other/:id', to: 'profile#other' 

  get 'friends/suscribe'

  post '/profile_other/:id', to: 'profile#update', as: 'profile'
  post '/profiled/:id', to: 'profile#destroy', as: 'deleted'

  get '/friends/notsuscribe', to: 'friends#notsuscribe'
  resources :friends
  resources :notes
  get 'welcome/index'
  resources :notifications do 
    collection do 
        post :mark_as_read
    end 
  end
  resources :gifts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	root :to => 'welcome#index'
	  get '/home' => 'home#index'


	  get '/auth/:provider/callback' => 'sessions#create'
	  get '/signin' => 'sessions#new', :as => :signin
	  get '/signout' => 'sessions#destroy', :as => :signout

end

hbd/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hbd/app/models/birth.rb
class Birth < ApplicationRecord
	has_attached_file :image, styles: { large: '600x600>', medium: '300x300>', thumb: '150x150#' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :user
end

hbd/app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

hbd/app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :user
has_attached_file :image, styles: { large: '600x600>', medium: '300x300>', thumb: '150x150#' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  scope :unread, ->{where read_at: nil}
end

hbd/app/models/note.rb
class Note < ApplicationRecord
	  has_attached_file :image, styles: { large: '600x600>', medium: '300x300>', thumb: '150x150#' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	
  belongs_to :user

end

hbd/app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :gift
  belongs_to :friend
end

hbd/app/models/user.rb
class User < ApplicationRecord
	has_many :gifts
	has_many :notes
	has_many :friends
	has_many :births
	 def self.create_with_omniauth(auth)
	   create! do |user|
	     user.provider = auth['provider']
	     user.uid = auth['uid']
	     if auth['info']
	       user.name = auth['info']['name'] || ""
	       user.email = auth['info']['email'] || ""

	     end
	   end
	 end

end

hbd/app/models/userprofile.rb
class Userprofile < ApplicationRecord
  belongs_to :user
end

hbd/app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]
  helper_method :current_user 


  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.where(user_id: current_user.id )
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create

    @gift = Gift.new(gift_params)
    @gift.user_id=current_user.id

     
    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      @user_id=current_user.id
      params.require(:gift).permit(:name_gift, :link_gift, :price_gift, :image)
    end

    def current_user
      return unless session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end

    def logged_in?
      !!session[:user_id]
    end
end

hbd/app/controllers/home_controller.rb
class HomeController < ApplicationController

	 helper_method :current_user 
  def index

  end
	
 private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end
	
end

hbd/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  helper_method :current_user 
  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.where(user_id: current_user.id )
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user_id= current_user.id
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      @note.user_id= current_user.id
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :text)
    end

    def current_user
      return unless session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end

    def logged_in?
      !!session[:user_id]
    end
end

hbd/app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

hbd/app/helpers/application_helper.rb
module ApplicationHelper
end

hbd/app/helpers/births_helper.rb
module BirthsHelper
end

hbd/app/helpers/friends_helper.rb
module FriendsHelper
end

hbd/app/helpers/gifts_helper.rb
module GiftsHelper
end

hbd/app/helpers/home_helper.rb
module HomeHelper
end

hbd/app/helpers/notes_helper.rb
module NotesHelper
end

hbd/app/helpers/profile_helper.rb
module ProfileHelper
end

hbd/app/helpers/sessions_helper.rb
module SessionsHelper
end

hbd/app/helpers/test_helper.rb
module TestHelper
end

hbd/app/helpers/userprofiles_helper.rb
module UserprofilesHelper
end

hbd/app/helpers/welcome_helper.rb
module WelcomeHelper
end

hbd/app/views/gifts/_form.html.erb
<%= form_with(model: gift, local: true) do |form| %>
  <% if gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% gift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name_gift %>
    <%= form.text_field :name_gift, id: :gift_name_gift %>
  </div>

  <div class="field">
    <%= form.label :link_gift %>
    <%= form.text_field :link_gift, id: :gift_link_gift %>
  </div>

  <div class="field">
    <%= form.label :price_gift %>
    <%= form.number_field :price_gift, id: :gift_price_gift %>
  </div>

   <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :gift_image_gift %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hbd/app/views/gifts/edit.html.erb
<section class="content-header">
  <h1>
    Editing Gift
    <small>Example 2.0</small>
  </h1>
</section>


<%= render 'form', gift: @gift %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

hbd/app/views/gifts/index.html.erb
<p id="notice"><%= notice %></p>

<section class="content-header">
  <h1>
    Gifts
    <small>Example 2.0</small>
  </h1>
</section>

<section class="content">

<div class="box box-info">
  <div class="box-header with-border">
    <h3 class="box-title">Latest Orders</h3>

  </div>

          <!-- /.box-header -->
<div class="box-body">
  <div class="table-responsive">

      <table class="table no-margin">
        <thead>
          <tr>
            <th>Name gift</th>
            <th>Link gift</th>
            <th>Price gift</th>
            <th>User</th>
            <th colspan="3"></th>
          </tr>
        </thead>

          <tbody>
            <% @gifts.each do |gift| %>
              <tr>
                <td><%= image_tag gift.image , alt: "Mon image", width: 64, height: 64 %></td>
                <td><%= gift.name_gift %></td>
                <td><%= gift.link_gift %></td>
                <td><%= gift.price_gift %></td>
                <td><%= gift.user.id %></td>
                <td><%= link_to 'Show', gift %></td>
                <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
                <td><%= link_to 'Destroy', gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
    </table>
  </div>
</div>
   <div class="box-footer clearfix">
              <%= link_to 'New Gift', new_gift_path ,class: 'btn btn-sm btn-info btn-flat pull-right' %>
   </div>
</div>
</section>
<br>

hbd/app/views/gifts/new.html.erb
<h1>New Gift</h1>

<%= render 'form', gift: @gift %>

<%= link_to 'Back', gifts_path %>

hbd/app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name gift:</strong>
  <%= @gift.name_gift %>
</p>

<p>
  <strong>Link gift:</strong>
  <%= @gift.link_gift %>
</p>

<p>
  <strong>Price gift:</strong>
  <%= @gift.price_gift %>
</p>
<p>
  <strong>User:</strong>
  <%= @gift.user.name %>
</p>

<%= link_to 'Edit', edit_gift_path(@gift) %> |
<%= link_to 'Back', gifts_path %>

hbd/app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :note_title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, id: :note_text %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hbd/app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

hbd/app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.text %></td>
        <td><%= note.user.name %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

hbd/app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

hbd/app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @note.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @note.user.name %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>