hbd/config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :userprofiles
  get 'test/index'

  resources :births
  get 'profile/my'

  get '/profile_other/:id', to: 'profile#other' 

  get 'friends/suscribe'

  post '/profile_other/:id', to: 'profile#update', as: 'profile'
  post '/profiled/:id', to: 'profile#destroy', as: 'deleted'

  get '/friends/notsuscribe', to: 'friends#notsuscribe'
  resources :friends
  resources :notes
  get 'welcome/index'
  resources :notifications do 
    collection do 
        post :mark_as_read
    end 
  end
  resources :gifts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	root :to => 'welcome#index'
	  get '/home' => 'home#index'


	  get '/auth/:provider/callback' => 'sessions#create'
	  get '/signin' => 'sessions#new', :as => :signin
	  get '/signout' => 'sessions#destroy', :as => :signout

end

hbd/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hbd/app/models/birth.rb
class Birth < ApplicationRecord
	has_attached_file :image, styles: { large: '600x600>', medium: '300x300>', thumb: '150x150#' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :user
end

hbd/app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

hbd/app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :user
has_attached_file :image, styles: { large: '600x600>', medium: '300x300>', thumb: '150x150#' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  scope :unread, ->{where read_at: nil}
end

hbd/app/models/note.rb
class Note < ApplicationRecord
	  has_attached_file :image, styles: { large: '600x600>', medium: '300x300>', thumb: '150x150#' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	
  belongs_to :user

end

hbd/app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :gift
  belongs_to :friend
end

hbd/app/models/user.rb
class User < ApplicationRecord
	has_many :gifts
	has_many :notes
	has_many :friends
	has_many :births
	 def self.create_with_omniauth(auth)
	   create! do |user|
	     user.provider = auth['provider']
	     user.uid = auth['uid']
	     if auth['info']
	       user.name = auth['info']['name'] || ""
	       user.email = auth['info']['email'] || ""

	     end
	   end
	 end

end

hbd/app/models/userprofile.rb
class Userprofile < ApplicationRecord
  belongs_to :user
end

hbd/app/controllers/home_controller.rb
class HomeController < ApplicationController

	 helper_method :current_user 
  def index

  end
	
 private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end
	
end

hbd/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:user_id, :gift_id, :friend_id, :type_notification, :link_notifcation)
    end
end

hbd/app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

hbd/app/helpers/application_helper.rb
module ApplicationHelper
end

hbd/app/helpers/births_helper.rb
module BirthsHelper
end

hbd/app/helpers/friends_helper.rb
module FriendsHelper
end

hbd/app/helpers/gifts_helper.rb
module GiftsHelper
end

hbd/app/helpers/home_helper.rb
module HomeHelper
end

hbd/app/helpers/notes_helper.rb
module NotesHelper
end

hbd/app/helpers/notifications_helper.rb
module NotificationsHelper
end

hbd/app/helpers/profile_helper.rb
module ProfileHelper
end

hbd/app/helpers/sessions_helper.rb
module SessionsHelper
end

hbd/app/helpers/test_helper.rb
module TestHelper
end

hbd/app/helpers/userprofiles_helper.rb
module UserprofilesHelper
end

hbd/app/helpers/welcome_helper.rb
module WelcomeHelper
end

hbd/app/views/notifications/_form.html.erb
<%= form_with(model: notification, local: true) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :notification_user_id %>
  </div>

  <div class="field">
    <%= form.label :gift_id %>
    <%= form.text_field :gift_id, id: :notification_gift_id %>
  </div>

  <div class="field">
    <%= form.label :friend_id %>
    <%= form.text_field :friend_id, id: :notification_friend_id %>
  </div>

  <div class="field">
    <%= form.label :type_notification %>
    <%= form.text_field :type_notification, id: :notification_type_notification %>
  </div>

  <div class="field">
    <%= form.label :link_notifcation %>
    <%= form.text_field :link_notifcation, id: :notification_link_notifcation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hbd/app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

hbd/app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Gift</th>
      <th>Friend</th>
      <th>Type notification</th>
      <th>Link notifcation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.user %></td>
        <td><%= notification.gift %></td>
        <td><%= notification.friend %></td>
        <td><%= notification.type_notification %></td>
        <td><%= notification.link_notifcation %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

hbd/app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

hbd/app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @notification.user %>
</p>

<p>
  <strong>Gift:</strong>
  <%= @notification.gift %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @notification.friend %>
</p>

<p>
  <strong>Type notification:</strong>
  <%= @notification.type_notification %>
</p>

<p>
  <strong>Link notifcation:</strong>
  <%= @notification.link_notifcation %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>