hbd/config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :userprofiles
  get 'test/index'

  resources :births
  get 'profile/my'

  get '/profile_other/:id', to: 'profile#other' 

  get 'friends/suscribe'

  post '/profile_other/:id', to: 'profile#update', as: 'profile'
  post '/profiled/:id', to: 'profile#destroy', as: 'deleted'

  get '/friends/notsuscribe', to: 'friends#notsuscribe'
  resources :friends
  resources :notes
  get 'welcome/index'
  resources :notifications do 
    collection do 
        post :mark_as_read
    end 
  end
  resources :gifts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	root :to => 'welcome#index'
	  get '/home' => 'home#index'


	  get '/auth/:provider/callback' => 'sessions#create'
	  get '/signin' => 'sessions#new', :as => :signin
	  get '/signout' => 'sessions#destroy', :as => :signout

end

hbd/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hbd/app/models/birth.rb
class Birth < ApplicationRecord
	has_attached_file :image, styles: { large: '600x600>', medium: '300x300>', thumb: '150x150#' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :user
end

hbd/app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

hbd/app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :user
has_attached_file :image, styles: { large: '600x600>', medium: '300x300>', thumb: '150x150#' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  scope :unread, ->{where read_at: nil}
end

hbd/app/models/note.rb
class Note < ApplicationRecord
	  has_attached_file :image, styles: { large: '600x600>', medium: '300x300>', thumb: '150x150#' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	
  belongs_to :user

end

hbd/app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :gift
  belongs_to :friend
end

hbd/app/models/user.rb
class User < ApplicationRecord
	has_many :gifts
	has_many :notes
	has_many :friends
	has_many :births
	 def self.create_with_omniauth(auth)
	   create! do |user|
	     user.provider = auth['provider']
	     user.uid = auth['uid']
	     if auth['info']
	       user.name = auth['info']['name'] || ""
	       user.email = auth['info']['email'] || ""

	     end
	   end
	 end

end

hbd/app/models/userprofile.rb
class Userprofile < ApplicationRecord
  belongs_to :user
end

hbd/app/controllers/births_controller.rb
class BirthsController < ApplicationController
  before_action :set_birth, only: [:show, :edit, :update, :destroy]
  helper_method :current_user,:largeimage
  # GET /births
  # GET /births.json
  def index
    @births = Birth.where(user_id: current_user.id )
  end

  # GET /births/1
  # GET /births/1.json
  def show
  end

  # GET /births/new
  def new
    @birth = Birth.new
  end

  # GET /births/1/edit
  def edit
  end

  # POST /births
  # POST /births.json
  def create
    @birth = Birth.new(birth_params)

    respond_to do |format|
      @birth.user_id= current_user.id
      if @birth.save
        format.html { redirect_to @birth, notice: 'Birth was successfully created.' }
        format.json { render :show, status: :created, location: @birth }
      else
        format.html { render :new }
        format.json { render json: @birth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /births/1
  # PATCH/PUT /births/1.json
  def update
    respond_to do |format|
      @birth.user_id= current_user.id
      if @birth.update(birth_params)
        format.html { redirect_to @birth, notice: 'Birth was successfully updated.' }
        format.json { render :show, status: :ok, location: @birth }
      else
        format.html { render :edit }
        format.json { render json: @birth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /births/1
  # DELETE /births/1.json
  def destroy
    @birth.destroy
    respond_to do |format|
      format.html { redirect_to births_url, notice: 'Birth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def largeimage
    "http://graph.facebook.com/#{current_user.uid}/picture?type=large"
    end


    # Use callbacks to share common setup or constraints between actions.
    def set_birth
      @birth = Birth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def birth_params
      params.require(:birth).permit(:title, :description,:image)
    end

    def current_user
      return unless session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end

    def logged_in?
      !!session[:user_id]
    end
end

hbd/app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]
  helper_method :current_user 


  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.where(user_id: current_user.id )
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create

    @gift = Gift.new(gift_params)
    @gift.user_id=current_user.id

     
    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      @user_id=current_user.id
      params.require(:gift).permit(:name_gift, :link_gift, :price_gift, :image)
    end

    def current_user
      return unless session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end

    def logged_in?
      !!session[:user_id]
    end
end

hbd/app/controllers/home_controller.rb
class HomeController < ApplicationController

	 helper_method :current_user 
  def index

  end
	
 private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end
	
end

hbd/app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

hbd/app/helpers/application_helper.rb
module ApplicationHelper
end

hbd/app/helpers/births_helper.rb
module BirthsHelper
end

hbd/app/helpers/friends_helper.rb
module FriendsHelper
end

hbd/app/helpers/gifts_helper.rb
module GiftsHelper
end

hbd/app/helpers/home_helper.rb
module HomeHelper
end

hbd/app/helpers/notes_helper.rb
module NotesHelper
end

hbd/app/helpers/profile_helper.rb
module ProfileHelper
end

hbd/app/helpers/sessions_helper.rb
module SessionsHelper
end

hbd/app/helpers/test_helper.rb
module TestHelper
end

hbd/app/helpers/userprofiles_helper.rb
module UserprofilesHelper
end

hbd/app/helpers/welcome_helper.rb
module WelcomeHelper
end

hbd/app/views/births/_form.html.erb
<%= form_with(model: birth, local: true) do |form| %>
  <% if birth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(birth.errors.count, "error") %> prohibited this birth from being saved:</h2>

      <ul>
      <% birth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :birth_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :birth_description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :birth_user_id %>
  </div>
   <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :gift_image_birth %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hbd/app/views/births/edit.html.erb
<h1>Editing Birth</h1>

<%= render 'form', birth: @birth %>

<%= link_to 'Show', @birth %> |
<%= link_to 'Back', births_path %>

hbd/app/views/births/index.html.erb
<p id="notice"><%= notice %></p>
   
<%= image_tag largeimage %>
<h1>Births</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @births.each do |birth| %>
      <tr>
        <td><%= image_tag birth.image , alt: "Mon image", width: 64, height: 64 %></td>
        <td><%= birth.title %></td>
        <td><%= birth.description %></td>
        <td><%= link_to 'Show', birth %></td>
        <td><%= link_to 'Edit', edit_birth_path(birth) %></td>
        <td><%= link_to 'Destroy', birth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Birth', new_birth_path %>

hbd/app/views/births/new.html.erb
<h1>New Birth</h1>

<%= render 'form', birth: @birth %>

<%= link_to 'Back', births_path %>

hbd/app/views/births/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @birth.image , alt: "Mon image", width: 64, height: 64 %>
</p>


<p>
  <strong>Title:</strong>
  <%= @birth.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @birth.description %>
</p>



<%= link_to 'Edit', edit_birth_path(@birth) %> |
<%= link_to 'Back', births_path %>